Hard code Agencies and other public bodies to 400+
alphagov/frontend pull request #2794
Opened 2021-06-02 16:08 UTC by huwd

We have had to update this number a lot[1].

Generally I think it looks really bad for our home page to have one
number, that you then click to find out the real number is
different. It's probably not a massive thing, but it bugs me and makes
us appear inaccurate, something to be avoided when we're shooting for
high levels of trust.

I've tried different ways of solving this.

[PR #2692](https://github.com/alphagov/frontend/pull/2692) tried an
approach of getting the content data API from
`/api/government/organisations` and then parsing out the correct data.

This works, but runs into a few issues that are documented on the PR.
The biggest one is that we would then be making two calls to the content
API, one for the home page and one for this. Our Architectual aspiration
here is to keep each page to a single content call.

I've gone back and [updated that branch with some further commits](https://github.com/alphagov/frontend/commit/af2c06b585064c0c4af1488db21f2684df3d2b46) that
work to change over use the GDS organsiations API.

This also works, however:
- It is a bit slow on a first call, it needs to get all subsequent pages
from the org API,
- It then needs to repeat a bunch of processing and filtering that
Whitehall currently does on the content item to separate out hte "Other
agencies and public bodies" from other types of organisation (note,
Tribunals are particularly interesting to filter!)
- Then render them

This adds quite a lot of complexity, potentially greater needs for
caching, and other concerns.

The alternative is to just not do any of that, and reduce the accuracy
of the number to 400+...

I've seen this agency number go as low as 405, so it is not impossible
we could end up with 399 agencies or fewer. So this does not entirely
solve the problem, but it really reduces the number of times I would
need to go back and make a change.

Plus there is precident for this.

On the [How government works page](https://www.gov.uk/government/how-government-works)
it just says 300+. Which is still true at present numbers.

This seems like a pragmatic solution to something that is a bit of a
marginal problem, but keep things accurate until the next redesign of
the page.

At that point it would be good to consider if there is still a need for
this section and if the real estate could be put to better use.

It ends up looking like this:
![image](https://user-images.githubusercontent.com/3694062/120514284-05e80f00-c3c5-11eb-9ec6-fcbbaca97e1c.png)

[1]: https://github.com/alphagov/frontend/issues/2542

⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

2021-06-02 16:11 UTC, owenatgov approved these changes
You're a sly one Mr Diprose. Added a non-blocking comment.

2021-06-02 16:11 UTC, owenatgov commented on app/views/homepage/index.html.erb
> +                <strong class="home-numbers__large">400+</strong>
Do you reckon there's any potential benefit to putting this in a translation file?

2021-06-02 16:21 UTC, richardTowers requested changes
Personally I think this is reasonable, but we should make sure we've got the okay from at least someone in design before we merge this.

Misusing a "request changes" review just to make sure that happens.

2021-06-03 13:07 UTC, richardTowers approved these changes
Looks good to me, and Mia's given it a 👍🏻 on slack too. Thanks Huw!

2021-06-03 13:11 UTC, chao-xian approved these changes
Nice work Huw! The Platform Health team are trying to move everything into translation files so this makes it easier for them too.

2021-06-03 13:14 UTC, merged